### ISSUE TITLE
$validate not able to resolve profile reference

### ISSUE THREAD

**Issue by shayaanmunshi** [FirelyTeam/Vonk.Facade.Starter#10]
I am trying to validate sample FHIR Observation on my local with US Core profile as per Vonk specification. The Operation outcome is negative. Is below request response correct?

http://10.100.84.88:7781/Observation/$validate?profile=http://hl7.org/fhir/us/core/StructureDefinition/us-core-observationresults

{
    "resourceType": "OperationOutcome",
    "id": "25531c61-81c6-4a53-ad54-6449eba25820",
    "meta": {
        "versionId": "3df6d290-0aea-4cb7-bb08-87913ce7af2d",
        "lastUpdated": "2019-04-12T18:47:48.2651865+00:00"
    },
    "issue": [
        {
            "severity": "error",
            "code": "incomplete",
            "details": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/dotnet-api-operation-outcome",
                        "code": "4000"
                    }
                ],
                "text": "Unable to resolve reference to profile 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-observationresults'"
            },
            "location": [
                "Observation"
            ]
        }
    ]
}

**Comment by mbaltus** [comment]
By default, a local Vonk only loads the FHIR core definitions, which do not include the us-core profiles. If you have not instructed your Vonk to load the us-code profiles, you will get the above error, since your Vonk will not know the profile you're trying to validate against.

Please check http://docs.simplifier.net/vonk/features/conformanceresources.html to see how this can be done. Specifically the part about loading profiles from Simplifier is useful in your case.
If you set this in your appsettings file, your Vonk will automatically load the profiles and will be able to validate against them:

```
"AdministrationImportOptions": {
  "SimplifierProjects": [
    {
      "Uri": "https://stu3.simplifier.net/US-Core",
      "BatchSize": "20"
    }
  ],
}
