### ISSUE TITLE
Running the Facade in R4 mode results in NotImplementedException when querying for ressources

### ISSUE THREAD

**Issue by FloSeidel** [FirelyTeam/Vonk.Facade.Starter#51]
I tried to convert the project for R4. While requesting the exact patient with it's id works just fine, the query ("{base}/Patient?_id=1") results in a NotImplementedException.

System.NotImplementedException: Please make sure your data storage plugin implements resources for information model Fhir4.0

> at Vonk.Facade.Relational.RelationalQueryFactory\`2.EntryInformationModel(String informationModel) in C:\agent\_work\24\s\src\Vonk.Facade.Relational\RelationalQueryFactory.cs:line 135
> at Vonk.Core.Repository.QueryBuilder\`1.InteractionFilter(SearchOptions options, Int32 level) in C:\agent\_work\24\s\src\Vonk.Core\Repository\QueryBuilder.cs:line 170
> at Vonk.Core.Repository.QueryBuilder\`1.Build() in C:\agent\_work\24\s\src\Vonk.Core\Repository\QueryBuilder.cs:line 42
> at Visi.Repository.ViSiSearchRepository.SearchPatient(IArgumentCollection arguments, SearchOptions options) in C:\Users\me\projects\Vonk.Facade.Starter-master\Visi.Repository\ViSiSearchRepository.cs:line 46
> at Visi.Repository.ViSiSearchRepository.Search(String resourceType, IArgumentCollection arguments, SearchOptions options) in C:\Users\me\projects\Vonk.Facade.Starter-master\Visi.Repository\ViSiSearchRepository.cs:line 36
> at Vonk.Core.Operations.Search.SearchService.Search(IArgumentCollection arguments, IVonkContext vonkContext) in C:\agent\_work\24\s\src\Vonk.Core\Operations\Search\SearchService.cs:line 80
> at Vonk.Core.Operations.Search.SearchService.Search(IVonkContext vonkContext) in C:\agent\_work\24\s\src\Vonk.Core\Operations\Search\SearchService.cs:line 44
> at Vonk.Core.Pluggability.VonkInteractionAsyncMiddleware\`1.<>c__DisplayClass10_0.<<ExecuteService>b__0>d.MoveNext() in C:\agent\_work\24\s\src\Vonk.Core\Pluggability\VonkInteractionMiddleware.cs:line 173

**Comment by cknaap** [comment]
We are adding documentation on this in https://github.com/simplifhir/simplifier-docs/pull/50.

The reason for the different behaviour is that a FHIR read operation is always executed across all informationmodels (STU3 and R4 now), since we don't allow the same id to be used in both. So the informationmodel is not added as a filter to the query.
But Patient?_id=1 is a FHIR search operation and in that the informationmodel from the request (based on the fhirVersion or otherwise) will automatically be added to the query, resulting in a call to IRepoQueryFactory.EntryInformationModel.

**Comment by FloSeidel** [comment]
Thank you! 
As a hint: maybe note where (which class) to add the given code snippet :). The former mentioned snippets are referring to (ViSi)SearchRepository while the override of the EntryInformationModel is located in the RelationalQueryFactory.
